### ISSUE TITLE
light_environment not working properly

### ISSUE THREAD

**Issue by KayvK** [thenayr/Half-Life-Alyx-SDK#6]
Remove issue pls

**Comment by KayvK** [comment]
Note: Compiling in "Standard" instead of "Final" makes it work, but it took a century to build the map.

**Comment by KayvK** [comment]
light_environment doesn't work properly after compiling in "standard". I am not sure if this is fixed with the "final" rendering mode,
(By not working properly, I mean that other light sources such as light_spot casts light, but under light_environment, it looks like mat_fullbright 1)

**Comment by TrainDoctor** [comment]
I feel it's more than likely you didn't bake your lighting. 

Try this guide: https://steamcommunity.com/sharedfiles/filedetails/?id=2072734641
and make sure you bake your lighting before building the map. (Doing a full compile.)

Please also provide images of the problem you're describing, and lastly. Do it on the appropriate project. This is an installer, not a the FGDs which actually configure the assets usable in the bootleg SDK: https://github.com/gvarados1/Half-Life-Alyx-FGD

**Comment by KayvK** [comment]
I made sure to bake lighting under "Preview baked lighting" and I did a full compile. I will provide screenshots tommorow.

**Comment by TrainDoctor** [comment]
> 
> 
> I made sure to bake lighting under "Preview baked lighting" and I did a full compile. I will provide screenshots tommorow.

That's all well and good, but it misses the point that this is not the appropriate place to be filing this issue.
